Vagrant.configure("2") do |config|
    config.vm.boot_timeout = 600

    # master
    %w{master}.each_with_index do |master_name, master_idx|
        config.vm.define master_name do |master_node|
            master_node.vm.provider "vmware_desktop" do |v|
                v.cpus = 2
                v.memory = 4096
                v.gui = false
                v.linked_clone = false
            end
            master_node.vm.box = "bento/ubuntu-20.04"
            master_node.vm.box_version = "202401.31.0"
            master_node.vm.hostname = "k8s-#{master_name}"
            master_node.vm.network "private_network", ip: "10.0.#{master_idx}.#{master_idx + 10}"
            master_node.vm.provision "shell", path: "scripts/common.sh"
            master_node.vm.provision "shell", path: "scripts/master.sh", env: {"IDX" => "#{master_idx}"}
        end
    end

    # worker
    %w{worker}.each_with_index do |worker_name, worker_idx|
        (1..1).each do |idx|
            config.vm.define "#{worker_name}-#{idx}" do |worker_node|
                worker_node.vm.provider "vmware_desktop" do |v|
                    v.cpus = 2
                    v.memory = 4096
                    v.gui = false
                    v.linked_clone = false
                end
                worker_node.vm.box = "bento/ubuntu-20.04"
                worker_node.vm.box_version = "202401.31.0"
                worker_node.vm.hostname = "k8s-#{worker_name}-#{idx}"
                worker_node.vm.network "private_network", ip: "10.0.#{worker_idx}.#{worker_idx + 100}"
                worker_node.vm.provision "shell", path: "scripts/common.sh"
                worker_node.vm.provision "shell", path: "scripts/worker.sh", env: {"IDX" => "#{worker_idx}"}
            end
        end
    end

    # cicd
    %w{cicd}.each_with_index do |cicd_name, cicd_idx|
        config.vm.define cicd_name do |cicd_node|
            cicd_node.vm.provider "vmware_desktop" do |v|
                v.cpus = 2
                v.memory = 2048
                v.gui = false
                v.linked_clone = false
            end
            cicd_node.vm.box = "bento/ubuntu-20.04"
            cicd_node.vm.box_version = "202401.31.0"
            cicd_node.vm.hostname = "k8s-#{cicd_name}"
            cicd_node.vm.network "private_network", ip: "10.0.#{cicd_idx}.#{cicd_idx + 50}"
            cicd_node.vm.provision "shell", path: "scripts/cicd.sh", env: {"IDX" => "#{cicd_idx}"}
        end
    end
end